---
title: "Create final sample (netmat, med, CNB)"
author: "Cedric Huchuan Xia"
date: "09/02/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, message = FALSE, warning = FALSE,
  results = FALSE, eval = TRUE, cache = TRUE,
	 fig.width = 7, fig.height = 7, tidy = TRUE
)
knitr::opts_knit$set(root.dir = '/data/joy/BBL/projects/xiaNetworkCca/sCCA/aim1/')
```


```{r load packages, message=FALSE, warning=FALSE, cache=TRUE}
setwd('/data/joy/BBL/projects/xiaNetworkCca/sCCA/aim1/')
source('./script/chxRinitFunc.R')
```

```{r compile a master training sample}
# load train-test split
sample_sub <- read.csv("./result/201701/go1train_subject.csv")

# apply subject-level exclusion
hx_qa <- read.csv("/data/joy/BBL/studies/pnc/n1601_dataFreezeDec2016/health/n1601_health_20161214.csv")
sample_hx <- merge(sample_sub,hx_qa)
sample_qa <- subset(sample_hx, healthExcludev2 == 0)

# apply strc exclusion
t1_qa <- read.csv("/data/joy/BBL/studies/pnc/n1601_dataFreeze2016/neuroimaging/t1struct/n1601_t1QaData_v2.csv")
sample_t1 <- merge(sample_qa, t1_qa)
sample_qa <- subset(sample_t1, t1Exclude == 0)

# load modality exclusion file from the data-freeze
mod_qa <- read.csv("/data/joy/BBL/studies/pnc/n1601_dataFreeze2016/neuroimaging/rest/n1601_RestQAData.csv")
sample_mod <- merge(sample_qa,mod_qa)
sample_qa <- subset(sample_mod, restExclude ==0)

sample_qa<-sample_qa[order(sample_qa$bblid),]
gdn_train_qa <- sample_qa
save(gdn_train_qa,file = "./result/201701/gdn_train_qa.RData")
```


### Concatenate DIT lausanne
```{r load appropriate network}
n_sample <- dim(sample_qa)[1]
sample_net<-array(NA, c(333, 333, n_sample))
for (i in 1:n_sample){
  scanid <- sample_qa$scanid[i]
  netpath<- paste("/data/joy/BBL/studies/pnc/n1601_dataFreeze2016/neuroimaging/rest/restNetwork_gordon/gordonNetworks/",scanid,"_GordonPNC_network.txt",sep="")
  sample_net[,,i] <- as.matrix(read.table(netpath))
  print(paste(i,"."," copying ",scanid,"_","gordon",sep=""))
  }
```

```{r save concatenated matrix}
gdn_train_net <- sample_net
save(gdn_train_net, file ="./result/201701/gdn_train_netmat.RData")
```

```{r make feature table of the matrix}
net_ft <-t(apply(sample_net,c(3),function(x) x[upper.tri(x, diag = F)]))
rownames(net_ft) <- sample_qa$bblid

gdn_train_net_ft <- net_ft
save(gdn_train_net_ft,file ="./result/201701/gdn_train_net_ft.RData")

```

#### Average Network of Power for all training subjects
```{r average power net mat, echo=FALSE }
net_ave <- apply(sample_net, c(1,2), function(x) mean(na.omit(x)))

gdn_train_ave <- net_ave
save(gdn_train_ave,file="./result/201701/gdn_train_ave.RData")

parcels <- read.csv('/data/joy/BBL/studies/pnc/n1601_dataFreeze2016/neuroimaging/rest/restNetwork_gordon/GordonParcels.csv')
parcelshem <- parcels[order(parcels$Hem,parcels$Community),]
parcelsmod <- parcels[order(parcels$Community),]
gdn_train_ave <- gdn_train_ave[parcelsmod$ParcelID,parcelsmod$ParcelID]
levelplot(gdn_train_ave, at = seq(-1,1,length=10),par.settings = BuRdTheme(),xlab='',ylab='',main="Gordon Train Set")
```



### Compile clinical data for the training data 
``` {r clinical}
load('./result/201701/med_impute.RData')
med.sample <- subset(med.final, is.element(med.final$bblid,sample_qa$bblid)) 
#save the 111 training sample
gdn_train_med<-med.sample
save(gdn_train_med,file= "./result/201701/gdn_train_med.RData")
```
#### There are `r dim(meddata112.train)[1]` subjects with `r dim(meddata112.train)[2]-1` clinical items
