---
title: "Select features"
author: "Cedric Huchuan Xia"
date: "10/27/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, message = FALSE, warning = FALSE,
  results = FALSE, eval = TRUE, cache = TRUE,
   fig.width = 10, fig.height = 7, tidy = TRUE
)
knitr::opts_knit$set(root.dir = '~/Google Drive/TDSlab/sCCA/aim1/')
```
  
```{r load data}
load("/data/joy/BBL/projects/xiaNetworkCca/sCCA/aim1/result/201701/gla_train_net_ft.RData")
net.ft.train <- gla_train_net_ft
```


```{r calculate covariance}
net_mad<- apply(net.ft.train,2,function(x) round(mad(x),digits=3))
  
# ggplot2 version
net_mad_order <- data.frame(numedge = as.factor(1:dim(net.ft.train)[2]),mad = net_mad[order(-net_mad)])
salient_percent <- c(quantile(net_mad,c(.95,.9,.75,.5),na.rm = T))
thresh <- c(1,sapply(seq_along(salient_percent),function(i) round(mean(which(net_mad_order$mad == salient_percent[i])))), dim(net.ft.train)[2])

net_mad_order$group <- as.factor(c(rep(1,thresh[2]),rep(2,thresh[3]-thresh[2]),rep(3,thresh[4]-thresh[3]),rep(4,thresh[5]-thresh[4]),rep(5,thresh[6]-thresh[5])))


p <- ggplot(net_mad_order,aes(numedge,mad)) +
     geom_bar(stat = 'identity',aes(fill= group,color=group)) +
     scale_fill_brewer() +
     scale_x_discrete(breaks=c(thresh,dim(net.ft.train)[2]),name = "Individual Edge") +
     scale_y_continuous(name = "Median Abs. Deviation") +
     theme_classic(base_size = 20) +
     annotate("text", x = thresh[1]+(thresh[2]-thresh[1])/2, y = 0.33,label = "95%",size =4.5,colour = "black" ) +
     annotate("text", x = thresh[2]+(thresh[3]-thresh[2])/2, y = 0.3,label = "90%",size =4.5,colour = "black" ) +
     annotate("text", x = thresh[3]+(thresh[4]-thresh[3])/2, y = 0.28,label = "75%",size =4.5,colour = "black" ) +
    annotate("text", x = thresh[4]+(thresh[5]-thresh[4])/2, y = 0.26,label = "50%",size =4.5,colour = "black" ) +
     theme(legend.position="none") +
    theme(axis.text.x=element_text(angle=90,hjust = 1,vjust = +0.5)) +
    ggtitle("Train Set") +
    theme(plot.title = element_text(hjust = 0.5))
p

```

```{r compile connectivity features and regress}
# Take the edges with non-zero mad
inc_idx <- which(net_mad>=net_mad_order$mad[3400])
inc_net <- net.ft.train[,inc_idx]


# Compile covariates
sample_qa$sex <- as.factor(sample_qa$sex)
sample_qa$race2 <- as.factor(sample_qa$race2)

# regress out covariates on the individual edges
net.rgr <- matrix(NA, nrow = dim(inc_net)[1], ncol = dim(inc_net)[2])
rownames(net.rgr) <- rownames(net.ft.train)
net.rgr <- apply(inc_net, 2, function(x) residuals.glm(glm(x ~ ageAtScan1 + 
    sex + race2 + restRelMeanRMSMotion, data = sample_qa), type = "response"))

# PCA-on these data
net.rgr.pca <-prcomp(net.rgr, center = FALSE)

gla.rgr.train <- net.rgr
gla.rgr.pca.train <- net.rgr.pca
save(gla.rgr.pca.train,gla.rgr.train,file='./result/201701/gla_regr_data.RData')

```



```{r visulize which features}
net.ft.train[,-inc_idx] <- NA
net.data <- net.ft.train
net.cln.aj <- array(NA, c(360,360,dim(net.data)[1]))
for (i in 1:dim(net.data)[1]) {
  tempmax <- net.cln.aj[ , ,i]
  tempmax[upper.tri(tempmax,diag=F)] <- as.numeric(net.data[i,])
  tempmax <- sna::symmetrize(tempmax,rule='upper')
  net.cln.aj[ , , i] <- tempmax
  print(paste('No.',i,'subject'))
}

net.cln.ave <- apply(net.cln.aj, c(1,2), function(x) mean(na.omit(x)))
plotlim <- max(abs(net.cln.ave),na.rm = T)
levelplot(net.cln.ave, at = seq(-plotlim,plotlim,length=10),par.settings = BuRdTheme(),xlab='',ylab='',main="Glasser Train Set")

gla.3k.train.ave <- net.cln.ave
gla.3k.train.idx <- inc_idx
save(gla.3k.train.ave,gla.3k.train.idx,file ="./result/201701/gla_3k_stats.RData")
```


