---
title: "Select features with only motion regressed"
author: "Cedric Huchuan Xia"
date: "10/27/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, message = FALSE, warning = FALSE,
  results = FALSE, eval = TRUE, cache = TRUE,
   fig.width = 10, fig.height = 7, tidy = TRUE
)
knitr::opts_knit$set(root.dir = '~/Desktop/BBL/')
```
  
```{r load data}
load("./projects/xiaNetworkCca/sCCA/aim1/result/201701/pwr_train_net_ft.RData")
power.ft.train <- pwr_train_net_ft
```


```{r calculate covariance}
power_mad<- apply(power.ft.train,2,function(x) round(mad(x),digits=4))
power_mad_order <- data.frame(numedge = as.factor(1:dim(power.ft.train)[2]),mad = power_mad[order(-power_mad)])
salient_percent <- c(quantile(power_mad,c(.95,.9,.75,.5),na.rm = T))
thresh <- c(1,sapply(seq_along(salient_percent),function(i) round(mean(which(power_mad_order$mad == salient_percent[i])))), dim(power.ft.train)[2])
power_mad_order$group <- as.factor(c(rep(1,thresh[2]),rep(2,thresh[3]-thresh[2]),rep(3,thresh[4]-thresh[3]),rep(4,thresh[5]-thresh[4]),rep(5,thresh[6]-thresh[5])))
inc_idx <- which(power_mad>=power_mad_order$mad[3410])
inc_net <- power.ft.train[,inc_idx]
