---
title: "Select features"
author: "Cedric Huchuan Xia"
date: "10/27/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, message = FALSE, warning = FALSE,
  results = FALSE, eval = TRUE, cache = TRUE,
   fig.width = 10, fig.height = 7, tidy = TRUE
)
knitr::opts_knit$set(root.dir = '~/Google Drive/TDSlab/sCCA/aim1/')
```
  
```{r load data}
load("/data/joy/BBL/projects/xiaNetworkCca/sCCA/aim1/result/201701/lau_train_net_ft.RData")
power.ft.train <- lau_train_net_ft
```


```{r calculate covariance}
power_mad<- apply(power.ft.train,2,function(x) round(mad(x),digits=3))

  
# ggplot2 version
power_mad_order <- data.frame(numedge = as.factor(1:dim(power.ft.train)[2]),mad = power_mad[order(-power_mad)])
salient_percent <- c(quantile(power_mad,c(.95,.9,.75,.5),na.rm = T))
thresh <- c(1,sapply(seq_along(salient_percent),function(i) round(mean(which(power_mad_order$mad == salient_percent[i])))), dim(power.ft.train)[2])

power_mad_order$group <- as.factor(c(rep(1,thresh[2]),rep(2,thresh[3]-thresh[2]),rep(3,thresh[4]-thresh[3]),rep(4,thresh[5]-thresh[4]),rep(5,thresh[6]-thresh[5])))


p <- ggplot(power_mad_order,aes(numedge,mad)) +
     geom_bar(stat = 'identity',aes(fill= group,color=group)) +
     scale_fill_brewer() +
     scale_x_discrete(breaks=c(thresh,dim(power.ft.train)[2]),name = "Individual Edge") +
     scale_y_continuous(name = "Median Abs. Deviation") +
     theme_classic(base_size = 20) +
     annotate("text", x = thresh[1]+(thresh[2]-thresh[1])/2, y = 0.33,label = "95%",size =4.5,colour = "black" ) +
     annotate("text", x = thresh[2]+(thresh[3]-thresh[2])/2, y = 0.3,label = "90%",size =4.5,colour = "black" ) +
     annotate("text", x = thresh[3]+(thresh[4]-thresh[3])/2, y = 0.28,label = "75%",size =4.5,colour = "black" ) +
    annotate("text", x = thresh[4]+(thresh[5]-thresh[4])/2, y = 0.26,label = "50%",size =4.5,colour = "black" ) +
     theme(legend.position="none") +
    theme(axis.text.x=element_text(angle=90,hjust = 1,vjust = +0.5)) +
    ggtitle("Train Set") +
    theme(plot.title = element_text(hjust = 0.5))
p

```

```{r compile connectivity features and regress}
# Take the edges with non-zero mad
power_mad 
inc_idx <- which(power_mad>=power_mad_order$mad[3400])
inc_net <- power.ft.train[,inc_idx]


# Compile covariates
sample_qa$sex <- as.factor(sample_qa$sex)
sample_qa$race2 <- as.factor(sample_qa$race2)

# regress out covariates on the individual edges
power.rgr <- matrix(NA, nrow = dim(inc_net)[1], ncol = dim(inc_net)[2])
rownames(power.rgr) <- rownames(power.ft.train)
power.rgr <- apply(inc_net, 2, function(x) residuals.glm(glm(x ~ ageAtScan1 + 
    sex + race2 + restRelMeanRMSMotion, data = sample_qa), type = "response"))

# PCA-on these data
power.rgr.pca <-prcomp(power.rgr, center = FALSE)

lau.rgr.train <- power.rgr
lau.rgr.pca.train <- power.rgr.pca
save(lau.rgr.pca.train,lau.rgr.train,file='./result/201701/lau_regr_data.RData')

```

```{r regress clinical features and regress}
load("/data/joy/BBL/projects/xiaNetworkCca/sCCA/aim1/result/201701/pwr_train_med.RData")
med <- pwr_train_med
med.torgr <- within(med, rm("bblid"))
rownames(med.torgr) <- med$bblid
#plot(skewness(med.torgr),main='Sknewness Analysis of Raw Clinical Features',xlab='Psychiatric Symptoms',ylab='Skewness')
#regress out the continous variables (SIPs)

med.rgr.cont <- apply(med.torgr[,1:12], 2, function(x) residuals.glm(glm(x ~ ageAtScan1 + 
    sex + race2, data = sample_qa ), type = "response"))
#regress out the binary variables (everything else)
med.rgr.binary <- apply(med.torgr[,13:111], 2, function(x) residuals.glm(glm(x ~ ageAtScan1 + 
    sex + race2, family= binomial(link="logit"),data = sample_qa ), type = "response"))

med.rgr <- cbind(med.rgr.cont,med.rgr.binary)
rownames(med.rgr) <- med$bblid
colnames(med.rgr) <- colnames(med.torgr)

plot(skewness(med.rgr),main='Skewness Analysis of Regressed Clinical Features',xlab='Psychiatric Symptoms',ylab='Skewness')

pwr_train_med_rgr <- med.rgr

save(pwr_train_med_rgr, file = "./result/201701/pwr_med_rgr_data.RData")

```

```{r visulize which features}
power.ft.train[,-inc_idx] <- NA
power.data <- power.ft.train
power.cln.aj <- array(NA, c(234,234,dim(power.data)[1]))
for (i in 1:dim(power.data)[1]) {
  tempmax <- power.cln.aj[ , ,i]
  tempmax[upper.tri(tempmax,diag=F)] <- as.numeric(power.data[i,])
  tempmax <- sna::symmetrize(tempmax,rule='upper')
  power.cln.aj[ , , i] <- tempmax
  print(paste('No.',i,'subject'))
}

power.cln.ave <- apply(power.cln.aj, c(1,2), function(x) mean(na.omit(x)))
plotlim <- max(abs(power.cln.ave),na.rm = T)
levelplot(power.cln.ave, at = seq(-plotlim,plotlim,length=10),par.settings = BuRdTheme(),xlab='',ylab='',main="Lausanne Train Set")

lau.3k.train.ave <- power.cln.ave
lau.3k.train.idx <- inc_idx
save(lau.3k.train.ave,lau.3k.train.idx,file ="./result/201701/lau_3k_stats.RData")
```


